
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consulterCompte", targetNamespace = "http://ws/", className = "proxy.ConsulterCompte")
    @ResponseWrapper(localName = "consulterCompteResponse", targetNamespace = "http://ws/", className = "proxy.ConsulterCompteResponse")
    @Action(input = "http://ws/BanqueService/consulterCompteRequest", output = "http://ws/BanqueService/consulterCompteResponse")
    public Compte consulterCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeCompte", targetNamespace = "http://ws/", className = "proxy.ListeCompte")
    @ResponseWrapper(localName = "listeCompteResponse", targetNamespace = "http://ws/", className = "proxy.ListeCompteResponse")
    @Action(input = "http://ws/BanqueService/listeCompteRequest", output = "http://ws/BanqueService/listeCompteResponse")
    public List<Compte> listeCompte();

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "counvertir", targetNamespace = "http://ws/", className = "proxy.Counvertir")
    @ResponseWrapper(localName = "counvertirResponse", targetNamespace = "http://ws/", className = "proxy.CounvertirResponse")
    @Action(input = "http://ws/BanqueService/counvertirRequest", output = "http://ws/BanqueService/counvertirResponse")
    public double counvertir(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
